#!/bin/bash -x

cp $1 ${HOME}/Repo/x86_64
cd ${HOME}/Repo/x86_64

repo-add modeler.db.tar.xz $1

cat << EOF | ftp -n ftp.webspace.virginmedia.com
user username password
cd modeler/x86_64
put modeler.db
put modeler.db.tar.xz
put $1
EOF

